bnf_file ::= production production_list;

production_list ::= production production_list | ;

production ::= ID EQUALS rhs END;

rhs ::= token_list opt_alternation;

opt_alternation ::= '|' token_list opt_alternation | ;

token_list ::= token token_list | ;

token ::= ID | TERM;